import Head from "next/head";
import { Layout } from "../components/common/Layout";
import Header from "../components/common/header/Header";
import Footer from "../components/common/footer/Footer";
import Cta from "../components/common/cta/Cta";
import HomeHero from "../components/home/HomeHero";
import HomeLinks from "../components/home/HomeLinks";
import HomeFeatures from "../components/home/HomeFeatures";

export default function Home() {
  return (
    <>
      <Head>
        <title>DESIGNO | HOME </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Header />
        <HomeHero />
        <HomeLinks />
        <HomeFeatures />
        <Cta />
      </Layout>
      <Footer />
    </>
  );
}
