import Head from "next/head";
import styles from "../styles/utils.module.css";
import { Layout } from "../components/common/Layout";
import Header from "../components/common/Header";
import Footer from "../components/common/Footer";
import HomePage from "../components/home/HomePage";

export default function Home() {
  return (
    <>
      <Head>
        <title>DESIGNO | HOME </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Header />
        <HomePage />
      </Layout>
      <Footer />
    </>
  );
}
